name: "jekyll"
description: "first attempt"
source:      ./
destination: ./_site
exclude: [.sass-cache,node_modules,sass,package.json,gruntfile.js,images-src,js/libs,js/custom,js/build,readme.md]
encoding: utf-8
paginate: 2
paginate_path: "blog/:num"
permalink: blog/:month-:day-:year/:title.html
excerpt_separator: <!--more-->
gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: "blog"
    values:
      layout: "posts"
